# Generated by Django 5.0.3 on 2025-05-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_NathySantos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={},
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
