# Generated by Django 5.0.3 on 2025-05-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_NathySantos', '0002_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'verbose_name': 'Categoría de Portafolio', 'verbose_name_plural': 'Categorías de Portafolio'},
        ),
    ]
